version: ~> 1.0

os:
  - linux

language: node_js

cache:
  directories:
    - ~/.npm
    - node_modules
    - ~/.sonar/cache

addons:
  sonarcloud:
    organization: "mocks-server"
    branch:
      name: "$TRAVIS_CURRENT_BRANCH"

node_js:
  - "v10.19.0"
  - "v12.16.1"
  - "v13.12.0"

script:
  - npm run lint
  - npm run test:ci
  - npm run coveralls

jobs:
  include:
    - stage: sonar
      script:
        - npm run test:coverage
        - sonar-scanner -Dsonar.login=${SONAR_TOKEN};
      if: env(SONAR_TOKEN) IS present
  allow_failures:
    - name: sonar
