version: ~> 1.0
import:
  - source: .travis.yml
    mode: deep_merge_prepend

jobs:
  include:
    - stage: deploy
      script:
        - echo "Deploying"
      deploy:
        provider: npm
        edge: true
        email: "javier.brea@gmail.com"
        api_key: "$NPM_TOKEN"
        on:
          tags: true
        skip_cleanup: true
